jsyiek/AU2

- AU2/frontends/inquirer_cli.py
- AU2/html_components/HTMLComponent.py
- AU2/html_components/HiddenTextbox.py
- AU2/html_components/Label.py
Any use of `config` settings will [insert a `HiddenTextbox`](https://github.com/jsyiek/AU2/blob/master/AU2/plugins/CorePlugin.py#L434) at the start of the HTMLComponents that identifies the plugin. This is because config is handled through an export in the `CorePlugin` and not natively in the front-end.
These are passed over by the Inquirer front-end, which means we need to force it to skip it when going backward. The code wasn't doing this.
Resolves bug found in https://github.com/jsyiek/AU2/pull/26
> Add `noInteraction` attribute to `HTMLComponent`, skip `noInteraction` elements in `inquirer_cli`

- AU2/frontends/inquirer_cli.py
- AU2/html_components/SimpleComponents/LargeTextEntry.py
- AU2/plugins/util/game.py
This PR implements escaping of `message` and `default` arguments of `inquirer` Questions to solve issue #19.
I have tested the entire assassin create / update and event create / update interfaces with values including {}, and there were no issues. Pages also generated correctly.
> [19] Escaped {} in inquirer arguments

- AU2/plugins/custom_plugins/TargetingPlugin.py
- AU2/test/plugins/util/custom_plugins/test_TargetingPlugin.py
**What is it**: A simple library class that can be used to emulate `print`-like behavior, but converts into a list of `Label`s behind the scene which can be accessed with `instance.get_prints()`
**What's changed**: Only `TargetingPlugin`, which was using raw Python `print`'s. As @NerdyNinja11 mentioned, this is not scalable with web UIs. Note that while the `SRCFPlugin` uses prints, I plan to disable this function in the web UI as the web server should run on the SRCF (so doesn't need an SSH/SFTP client). 
**Testing**: I've printed out the targeting graph and tested its associated functions.
> Print using labels in TargetingPlugin

- AU2/database/model/Assassin.py
- AU2/plugins/CorePlugin.py
This is the "minimum change" for issue #57.
This PR doesn't change the plugin framework, but changes the `options_functions` of Event -> Update to instead return a list of tuples, where the first part of each tuple is what is displayed to the user and the second part is what will be passed to the plugin's `ask` function. The options are also sorted by event datetime, in reverse chronological order.
The display value of each event is the datetime + truncated headline. This means it no longer includes the internal identifier for the event; I'd be interested in hearing thoughts about this.
>  [57] Display datetimes in event selector of Event -> Update

- AU2/plugins/CorePlugin.py
- AU2/plugins/custom_plugins/BountyPlugin.py
- AU2/plugins/custom_plugins/TargetingPlugin.py
- AU2/plugins/custom_plugins/html_templates/bounties.html
Closes #60 
**Problem**: A player may end up placing a bounty on another player within the next day or so. This one slipped through the cracks of AU2 development as it was previously incorporated into the `MafiaPlugin` (which is now seriously out-of-date) and so didn't get an issue created back during the first AU2 development rush (meaning it wasn't taken in the second).
**Solution**: A simple bounty plugin. After discussion with the umpires, we're OK with the target's and bounty placer's names being public information. These do not use events unlike wantedness/etc. as there is no time expiry that makes sense to associate with a bounty. It's also a very rare occurrence and I'm not keen to put more questions on the umpire's to-do list whenever they add the event ("make the common case …
> [60] Bounty plugin

- AU2/database/AssassinsDatabase.py
- AU2/database/model/Assassin.py
- AU2/frontends/inquirer_cli.py
- AU2/plugins/CorePlugin.py
- AU2/plugins/custom_plugins/SRCFPlugin.py
- AU2/plugins/custom_plugins/UIConfigPlugin.py
This allows the umpire to toggle the visibility for each assassin.
An assassin is hidden by setting its `hidden` attribute to `True`.
Hidden assassins are not included in the options for `Assassin -> Update` or in the `AssassinPseudonymPair` component of `Event -> Create`.
Hidden assassins that are *already* in the event are included in the `AssassinPseudonymPair` component of `Event -> Update`, but the rest are not.
Hiding an assassin has no other effects currently. In particular, it has no effect on `TargetingPlugin` or sending emails with `SRCFPlugin`.
> [44] Added Assassin -> Hide export

- AU2/database/AssassinsDatabase.py
- AU2/database/model/Assassin.py
- AU2/plugins/CorePlugin.py
- AU2/plugins/custom_plugins/PolicePlugin.py
- AU2/test/plugins/util/custom_plugins/test_PolicePlugin.py
- AU2/test/test_utils.py
This builds on PR #59 to address issue #63.
It adds a new `Assassin -> Resurrect as Police` export to ~~`CorePlugin`~~ (EDIT: moved to `PolicePlugin`). The user selects from all *dead, non-police, non-hidden* assassins, and is prompted to give a new initial pseudonym for the selected assassin. The assassin is then cloned (with a new identifier), with the clone set to be police and have the entered pseudonym as its sole pseudonym.
> [63] Assassin -> Resurrect as Police

- AU2/database/model/Assassin.py
- AU2/database/model/Event.py
- AU2/frontends/inquirer_cli.py
- AU2/html_components/SimpleComponents/FloatEntry.py
- AU2/html_components/SimpleComponents/OptionalDatetimeEntry.py
- AU2/plugins/custom_plugins/ScoringPlugin.py
- AU2/plugins/custom_plugins/html_templates/openseason.html
- AU2/plugins/util/ScoreManager.py
- AU2/plugins/util/date_utils.py
- AU2/test/plugins/util/custom_plugins/test_ScoringPlugin.py
- AU2/test/test_utils.py
Adds a plugin to generate the Open Season page. The plugin includes config options to set the start of open season and the scoring formula. The start of open season determines whether the open season page is generated when using `Generate Pages`. If the start of open season is unset it defaults to assuming open season has *not* started.
~~The scoring formula is not used yet as I was waiting on @jsyiek 's solution to #31.~~ As a hotfix an `eval()` is used to parse the scoring formula.
The plugin uses a `ScoreManager` to calculate the kills, attempts, and conkers of each player; I have written a couple of automated tests already but it could perhaps do with more. I have also tested generating the open season page with the current game database, alternately using conkers, kills, and attempts …
> [13] Open season and Scoring plugin

- AU2/__init__.py
fixes #53, after way too much trial and error
> [53] notepad via pyinquirer on windows uses utf-8 by default

- AU2/plugins/custom_plugins/SRCFPlugin.py
Fixes #82 by adding `Content-Type: text/plain; charset=UTF-8` to email headers.
I have tested this works by sending an email to @NerdyNinja11 after making this change.
> [82] Add encoding info (utf-8) to email headers

- AU2/plugins/CorePlugin.py
- AU2/plugins/sanity_checks/MissingHtmlSpecifier.py
- AU2/plugins/sanity_checks/__init__.py
- AU2/plugins/sanity_checks/model/SanityCheck.py
- AU2/plugins/util/game.py
Implements #80 
**Problem**: There are some usability issues with AU2 - to name a few, umpires occasionally mistype [P38] as [38] or forget to put `` in front of an HTML report. There's not a good error-checking facility in the tool to pick up on these unavoidable occasional mistakes, leading to these bleeding into production webpages.
**Solution**: I've implemented an extensible sanity checking framework - only requiring two functions to be implemented per sanity check. I've implemented one check for now as a proof of concept - hopefully we can work together to add more in future.
This was not trivial to do, because we really need the following requirements:
- Must not introduce more exports (an error-checking facility you can forget to click isn't useful)
- Must not be its own plugin …
> [80] Sanity checking framework

- AU2/frontends/inquirer_cli.py
- AU2/html_components/SpecialComponents/ConfigOptionsList.py
- AU2/plugins/AbstractPlugin.py
- AU2/plugins/CorePlugin.py
- AU2/plugins/custom_plugins/CompetencyPlugin.py
- AU2/plugins/custom_plugins/TargetingPlugin.py
- requirements.txt
**Problem:** Certain config options (mainly to do with targeting) break the game if changed after a game has started. It would be useful to communicate this to users.
**Solution:** Have a subclass of `ConfigExport` called `DangerousConfigExport`, and have these coloured red in `Plugin config -> Plugin-specific parameters`. The config options I have classed as being dangerous are
- `Competency -> Change Auto Competency`
- `Targeting Graph -> Set player seeds`
- `Targeting Graph -> Set random seed`
**Remarks:**` gather_config_names` had to be reworked since otherwise the ANSI codes messed with the ordering of the config options. The module`colorama` is used in `inquirer_cli` to ensure the ANSI codes are rendered correctly on Windows (this is only an issue for older terminals), but not …
> Implemented `DangerousConfigExport`

- AU2/frontends/inquirer_cli.py
As it is unnecessary now that colouring is not the only safeguard against accessing DangerousConfigExports after game start.
> Remove `colorama` warning

- AU2/plugins/util/game.py
This is an implementation of @NerdyNinja11's suggestion for dealing with #89 — i.e. by adding `<br />`s when rendering plaintext reports.
> [89] Make `soft_escape` convert newlines into <br /> after escaping

- AU2/plugins/sanity_checks/IncorrectPseudonymFormatter.py
- AU2/plugins/sanity_checks/__init__.py
Implements #90 
**Problem**: Umpires sometimes put [X] instead of [PX]. 
**Solution**: This sanity check asks the umpires if they want to replace [X] with [PX]. Currently, the only instances in prod of this are in Peter and Emma's reports, and both are meant to represent references - so I'll need to let the umpires know of the change and make sure they don't choose to replace them!
> [90] Sanity check - [X] instead of [PX]

- AU2/__init__.py
- AU2/database/model/Assassin.py
- AU2/frontends/inquirer_cli.py
- AU2/plugins/custom_plugins/CompetencyPlugin.py
- AU2/plugins/custom_plugins/PageGeneratorPlugin.py
- AU2/plugins/custom_plugins/ScoringPlugin.py
- AU2/plugins/custom_plugins/html_templates/stats.html
- AU2/plugins/util/ScoreManager.py
- AU2/plugins/util/date_utils.py
- requirements.txt
This PR adds an export `Scoring -> Generate stats page` to `ScoringPlugin`.
The stats page is configurable, allowing the user to select which columns should be included. In addition to the standard columns
- Real Name
- Pseudonym
- Number of Kills
- Conkers Score
there is the option to include
- Number of Attempts
- Score (as calculated for Open Season)
- Died at (which includes a link to the relevant event)
- Position (which is just where the player appears in the ordering used on the stats page)
The user can choose between two ordering options: by number of kills (the way recent stats pages have been ordered), or based on order of death (the way stats pages were ordered previously).
Furthermore there is an option to generate a visualisation of the kill graph using `pyvis`. This is …
> [73] Stats Page

- AU2/frontends/inquirer_cli.py
- AU2/plugins/CorePlugin.py
**Problem:** As described by @NerdyNinja11 in #74, now that we have more plugins and exports it can get unwieldy navigating through the menu. We do already have a feature to hide certain menu items, but for functionality that is used occasionally it is cumbersome to have to un-suppress an export to use it and then re-suppress it afterwards; it would be much more useful to be able to keep most of the exports visible on the main menu but put the most frequently used ones at the top.
**Solution:** I have implemented a simple "pinning" system for exports: the ConfigExport `CorePlugin -> Pin menu options` can be used to select exports to be "pinned". Pinned exports are listed before non-pinned exports in the main menu. (Within each category, exports are ordered by display name as before).
I …
> [74] Allow frequently-used Exports to be pinned for ease of use

- AU2/plugins/custom_plugins/PlayerImporterPlugin.py
**Problem:** The umpires this term have had issues with importing assassins from the signups spreadsheet. We eventually figured out that it was a file permissions issue. Since I do not know Windows well enough I was unable to advise how to fix this. In future this potential issue form part of the handover materials, but it's better for the umpires to not have to deal with this at all.
**Solution:** I have created an Import function which takes the URL of a (publicly accessible) Google Sheet and downloads the CSV of it, then imports from this.
I have also made the importer able to cope with spreadsheets containing blank rows above the headers, and added graceful handling of `PermissionError`s.
**Limitations:** Of course, this is reliant on Google's endpoints remaining reliable (which, …
> [PlayerImporterPlugin] Player importer from Google Sheets

- AU2/frontends/inquirer_cli.py
**Problem:** It is possible for umpires to specify which pseudonym should by rendered in a report using the [PX_i] format. However, the index *i* may differ from its position in the list of pseudonyms shown by `Assassin -> Update`. This is because pseudonyms keep their indices even when a pseudonym with a lower index is deleted.
**Solution:** Show the index of each pseudonym in the pseudonym editing interface `EditablePseudonymList`.
**Alternative idea:** Don't hide blank pseudonyms in `EditablePseudonymList` (but still treat blank pseudonyms as deleted when rendering pages).
> Include pseudonym index in `EditablePseudonymList`

- .idea/misc.xml
- AU2/plugins/CorePlugin.py
- AU2/plugins/custom_plugins/SRCFPlugin.py
**Problem:** See #102. Additionally, the naming convention for backups mean that they aren't ordered correctly when sorted by name.
**Solution:** This PR implements automatic backups whenever `SRCF -> Upload database and PUBLISH PAGES` or `SRCF -> Upload database and SEND EMAILS` is run. The name of the backup takes the format `backup_<date>_<time>_<username>_auto`, where `<date>` is in YYYY-MM-DD format. I have also changed the suggested manual backup name to go along with this format (but without the `_auto`).
This doesn't *fully* implement #102, since backups aren't created when syncing the database at startup or when running `SRCF -> Manual database sync`, but we do want to avoid creating an excessive number of backups.
For the sorting problem, I have implemented a custom sorting key …
> [102] [SRCFPlugin] Auto-backups and remote backup sorting

- AU2/plugins/sanity_checks/PlayerNotDead.py
- AU2/plugins/sanity_checks/__init__.py
This sanity check detects when pseudonym specifiers of the form `[DX]` or `[NX]` are used in the headline or reports of an event where the player with secret id `X` did not die in that event, and suggests replacing these with `[PX]` (for the same value of `X`).
> [92] Sanity check for when player not dead but [DX] or [NX] used.

- AU2/plugins/custom_plugins/PolicePlugin.py
Currently, police hidden using `Assassin -> Hide` are still listed on the police page.
This is not intuitive behaviour, and there are usecases for wanting to hide police (e.g., if the umpire wants to use a "dummy" player to represent a civilian, then such a player would currently appear on the police page even if set to hidden. In the previous game (Mich 2024), the umpires created a non-police dummy assassin, which would have been catastrophic for targeting if it hadn't been open season).
This PR stops hidden police from being included on the police page.
> Don't include hidden police on police page

- AU2/database/AssassinsDatabase.py
- AU2/plugins/CorePlugin.py
- AU2/plugins/custom_plugins/CompetencyPlugin.py
- AU2/plugins/custom_plugins/ScoringPlugin.py
- AU2/plugins/util/ScoreManager.py
- AU2/plugins/util/game.py
See #115.
For this I have introduced a core "game end" config setting, which triggers stats page generation. The idea is that this parameter would also allow AU2 to distinguish the duel from the rest of the game.
Moreover
- the AU1-style ordering on the stats page uses its value to keep duellists near the top of the ranking
- the open season page is 'frozen' at its end of game state (i.e. duellists will not be removed if they die in the duel)
- when generating pages, the date to calculate incos for defaults to the end of game when generating pages after the end of game
> [115] Refactored stats page generation to use `Generate pages`

- AU2/frontends/inquirer_cli.py
- AU2/html_components/SimpleComponents/Checkbox.py
- AU2/plugins/CorePlugin.py
**Problem:** It is currently possible to create a non-Police assassin once a game has started, even though this messes up the targeting graph.
**Solution:** Initially I was going to use `get_game_start` for this, but I realised that this wouldn't work because it defaults to the current datetime so is not a reliable indicator that that game has actually started. So instead I use the `last_emailed_event` stored in the GenericStateDatabase by `TargetingPlugin` when emails are sent, to determine whether the game has started or not. This is actually precisely what we want, because the whole point here is stopping the targeting graph completely changing, which only matters once targets have been sent out!
**Testing:** Manual.
> [116] Prevent creation of non-Police assassins after first email

- AU2/plugins/custom_plugins/CompetencyPlugin.py
- AU2/plugins/util/CompetencyManager.py
- AU2/test/plugins/util/custom_plugins/test_CompetencyPlugin.py
- AU2/test/test_utils.py
**Problem:** Currently, the "list of corpses" on the inco list page has been disabled. This is because of a logic error: the current code shows a list of *incos who are currently dead* rather than *players who died whilest inco*.
**Solution:** `CompetencyManager` now also tracks a list of corpses of players who died while inco. This only works correctly if events are added to the manager in chronological order (as `CompetencyPlugin` does).
**Testing:** Manual.
I created events both where a player died while inco and where a player died while not inco, then generated the page inco page for after the latter's inco deadline had passed. Only the former player was included in the list of corpses.
> [122] Fixed list of corpses on inco list page

- AU2/database/model/Event.py
- AU2/html_components/SimpleComponents/InputWithDropDown.py
- AU2/html_components/SimpleComponents/Table.py
- AU2/plugins/AbstractPlugin.py
- AU2/plugins/CorePlugin.py
- AU2/plugins/custom_plugins/CompetencyPlugin.py
- AU2/plugins/custom_plugins/TargetingPlugin.py
- AU2/plugins/custom_plugins/UIConfigPlugin.py
- AU2/plugins/custom_plugins/WantedPlugin.py
Implements #125 
**Problem**: There's currently no easy way to see a quick snapshot of what happened in an event or a player (you need to go through the update tool, which is far from rapid).
**Solution**: Add some `CorePlugin` functionality to render events & assassins with help from subordinate plugins.
Comes with a tweak in the UIConfigPlugin to make assassins in the status area searchable :-) 
Threw this together in an hour or so... feel free to take a fine-toothed comb to it and be nitpicky.
> [125] Player & event status exports

- AU2/plugins/custom_plugins/MayWeekUtilitiesPlugin.py
- AU2/plugins/custom_plugins/ScoringPlugin.py
- AU2/plugins/custom_plugins/html_templates/may_week_utils_news.html
- AU2/plugins/util/render_utils.py
**Problem:** The problem is twofold
1. `PageGeneratorPlugin` paginates news into weeks (and puts a 'Week N' heading at the top), which isn't suitable for May Week, where the news should all be on one page
2. `PageGeneratorPlugin` colours names incorrectly -- not just wrt having names coloured in team colours, but also because casual players get rendered in police colours, and permadeath applies
**Solution:** Have `MayWeekUtilitiesPlugin` generate its own news page. I have modified `render_utils` to make it possible for the plugin to override colouring but otherwise use common news generation code.
Team colours are rendered according to the player's team at the time of the event, rather than when the page is generated.
I have also taken the opportunity to resolve #99.
**Testing:** Manual. …
> May Week News page
